// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA27c2e9aDecodeGithubComK0st1aGophermartInternalAdaptersApiRestModels(in *jlexer.Lexer, out *Withdrawals) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Withdrawals, 0, 1)
			} else {
				*out = Withdrawals{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 WithdrawOut
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA27c2e9aEncodeGithubComK0st1aGophermartInternalAdaptersApiRestModels(out *jwriter.Writer, in Withdrawals) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Withdrawals) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA27c2e9aEncodeGithubComK0st1aGophermartInternalAdaptersApiRestModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Withdrawals) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA27c2e9aEncodeGithubComK0st1aGophermartInternalAdaptersApiRestModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Withdrawals) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA27c2e9aDecodeGithubComK0st1aGophermartInternalAdaptersApiRestModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Withdrawals) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA27c2e9aDecodeGithubComK0st1aGophermartInternalAdaptersApiRestModels(l, v)
}
func easyjsonA27c2e9aDecodeGithubComK0st1aGophermartInternalAdaptersApiRestModels1(in *jlexer.Lexer, out *WithdrawOut) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.Order = int64(in.Int64Str())
		case "sum":
			out.Sum = float64(in.Float64())
		case "processed_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ProcessedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA27c2e9aEncodeGithubComK0st1aGophermartInternalAdaptersApiRestModels1(out *jwriter.Writer, in WithdrawOut) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.Int64Str(int64(in.Order))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Sum))
	}
	{
		const prefix string = ",\"processed_at\":"
		out.RawString(prefix)
		out.Raw((in.ProcessedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawOut) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA27c2e9aEncodeGithubComK0st1aGophermartInternalAdaptersApiRestModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawOut) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA27c2e9aEncodeGithubComK0st1aGophermartInternalAdaptersApiRestModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawOut) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA27c2e9aDecodeGithubComK0st1aGophermartInternalAdaptersApiRestModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawOut) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA27c2e9aDecodeGithubComK0st1aGophermartInternalAdaptersApiRestModels1(l, v)
}
